services:

  discover:
    image: discover
    build:
      context: discover
      dockerfile: ./Dockerfile
    ports:
      - 8099:8099
  
  api-gateway:
    image: api-gateway
    build:
      context: api-gateway
      dockerfile: ./Dockerfile
    ports:
      - 50000:50000

  demo-rest-clientes:
    image: demo-rest-clientes
    build:
      context: demo-rest-clientes 
      dockerfile: ./Dockerfile
    ports:
      - 50001:50001


  demo-rest-productos:
    image: demo-rest-productos
    build:
      context: demo-rest-productos
      dockerfile: ./Dockerfile
    ports:
      - 50002:50002

  demo-rest-ventas:
    image: demo-rest-ventas   
    build:
      context: demo-rest-ventas
      dockerfile: ./Dockerfile  
    ports:
      - 50003:50003 

  demo-rest-busquedas:
    image: demo-rest-busquedas    
    build:
      context: demo-rest-busquedas
      dockerfile: ./Dockerfile
    ports:
      - 50004:50004 